"""removed unique constraint of vehicle number in service bookings

Revision ID: 90fcbb1b6b72
Revises: a844ea9273b3
Create Date: 2024-11-05 14:36:04.055825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fcbb1b6b72'
down_revision = 'a844ea9273b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicebookings', schema=None) as batch_op:
        batch_op.drop_constraint('servicebookings_vehicle_number_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicebookings', schema=None) as batch_op:
        batch_op.create_unique_constraint('servicebookings_vehicle_number_key', ['vehicle_number'])

    # ### end Alembic commands ###
