"""created drivers table

Revision ID: a0ae7a9bd50d
Revises: b6d7ed4b0b9d
Create Date: 2024-10-28 15:39:24.020976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ae7a9bd50d'
down_revision = 'b6d7ed4b0b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('driver_name', sa.String(length=80), nullable=False),
    sa.Column('driver_age', sa.Integer(), nullable=False),
    sa.Column('driver_email', sa.String(length=120), nullable=False),
    sa.Column('driver_mobile', sa.String(length=15), nullable=False),
    sa.Column('driver_password', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('driver_id'),
    sa.UniqueConstraint('driver_email'),
    sa.UniqueConstraint('driver_mobile')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drivers')
    # ### end Alembic commands ###
