"""added booking_id as foreign key to notifications table

Revision ID: abdeddff2a7b
Revises: e472635a1139
Create Date: 2024-11-12 13:26:59.656919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abdeddff2a7b'
down_revision = 'e472635a1139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'servicebookings', ['booking_id'], ['booking_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('booking_id')

    # ### end Alembic commands ###
