"""Renamed first_name and last_name columns

Revision ID: afbcacaf678c
Revises: b0268da0ee3d
Create Date: 2024-09-18 12:59:47.527862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afbcacaf678c'
down_revision = 'b0268da0ee3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name', new_column_name='firstName')
        batch_op.alter_column('last_name', new_column_name='lastName')
        batch_op.alter_column('phone_number', new_column_name='phoneNumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('firstName', new_column_name='first_name')
        batch_op.alter_column('lastName', new_column_name='last_name')
        batch_op.alter_column('phoneNumber', new_column_name='phone_number')


    # ### end Alembic commands ###
