"""foreignkey userid added to service bookings

Revision ID: b6d7ed4b0b9d
Revises: 43959c890348
Create Date: 2024-10-25 14:56:39.462170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision = 'b6d7ed4b0b9d'
down_revision = '43959c890348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicebookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', UUID(as_uuid=True), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicebookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
