"""admins created

Revision ID: bf6a7355e1d4
Revises: afbcacaf678c
Create Date: 2024-09-27 13:06:05.318949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Table, MetaData
from werkzeug.security import generate_password_hash


# revision identifiers, used by Alembic.
revision = 'bf6a7355e1d4'
down_revision = 'afbcacaf678c'
branch_labels = None
depends_on = None

metadata = MetaData()

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('adminName', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('phoneNumber', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phoneNumber')
    )
    # ### end Alembic commands ###

    admins_table = Table('admins', metadata, autoload_with=op.get_bind())

    op.bulk_insert(
        admins_table,
        [
            {
                'adminName': 'ytp1',
                'email': 'ytp1@example.com',
                'password': generate_password_hash('password123'),  # Hash the password
                'phoneNumber': '1234567890',
            },
            {
                'adminName': 'ytp2',
                'email': 'ytp2@example.com',
                'password': generate_password_hash('password456'),  # Hash the password
                'phoneNumber': '0987654321',
            },
        ]
    )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    # ### end Alembic commands ###
